//! Compositor detection and launch

use anyhow::{bail, Context, Result};
use std::process::Command;
use tracing::{debug, info};

use crate::config::CompositorConfig;

/// Available compositor backends
#[derive(Debug, Clone, PartialEq)]
pub enum Backend {
    /// River — Wayland compositor (zig-based, minimal)
    River,
    /// Cage — Single-window Wayland compositor (C, wlroots)
    Cage,
    /// Sway — Full tiling Wayland compositor (C, wlroots)
    Sway,
}

/// Detect the best available compositor backend
pub fn detect_backend(config: &CompositorConfig) -> Result<Backend> {
    // If user specified a backend, use it
    if config.backend != "auto" {
        return match config.backend.as_str() {
            "river" => Ok(Backend::River),
            "cage" => Ok(Backend::Cage),
            "sway" => Ok(Backend::Sway),
            other => bail!("Unknown compositor backend: {}", other),
        };
    }

    // Auto-detect: prefer river (lightest) → cage → sway
    if which::which("river").is_ok() {
        info!("Detected: river");
        return Ok(Backend::River);
    }

    if which::which("cage").is_ok() {
        info!("Detected: cage");
        return Ok(Backend::Cage);
    }

    if which::which("sway").is_ok() {
        info!("Detected: sway");
        return Ok(Backend::Sway);
    }

    bail!("No Wayland compositor found. Install river, cage, or sway.")
}

/// Launch the compositor with Hope OS configuration
pub fn launch(backend: &Backend, config: &CompositorConfig) -> Result<()> {
    info!("Launching {:?} compositor...", backend);

    let mut cmd = match backend {
        Backend::River => {
            let c = Command::new("river");
            // River uses riverctl for configuration
            // We'll set up config via environment
            c
        }
        Backend::Cage => {
            let c = Command::new("cage");
            // Cage is single-window, good for kiosk mode
            c
        }
        Backend::Sway => {
            let c = Command::new("sway");
            // Sway uses sway config
            // We'll generate a Hope-themed config
            generate_sway_config(config)?;
            c
        }
    };

    // Set environment for Wayland
    cmd.env("WAYLAND_DISPLAY", "wayland-1");
    cmd.env("XDG_RUNTIME_DIR", "/run/user/1000");

    if config.xwayland {
        debug!("XWayland enabled");
    }

    if config.direct_scanout {
        debug!("Direct scanout enabled (gaming mode)");
    }

    let status = cmd.status().context("Failed to start compositor")?;

    if !status.success() {
        bail!("Compositor exited with status: {}", status);
    }

    Ok(())
}

/// Generate a Hope-themed Sway configuration
fn generate_sway_config(config: &CompositorConfig) -> Result<()> {
    let config_dir = dirs::config_dir()
        .context("Could not determine config dir")?
        .join("sway");
    std::fs::create_dir_all(&config_dir)?;

    let sway_config = format!(
        r#"# Hope OS — Sway Configuration
# Generated by hope-shell

# Deep Space Theme
set $bg #0F0F12
set $fg #E0E0E8
set $primary #6366F1
set $secondary #8B5CF6
set $tertiary #06B6D4

# Appearance
default_border pixel 2
default_floating_border pixel 2
border_radius 8
blur enable
blur_radius 5
shadows enable
shadow_radius 10

# Gaps
gaps inner 8
gaps outer 4

# Colors
client.focused $primary $primary $fg $primary
client.focused_inactive $bg $bg $fg $bg
client.unfocused $bg $bg $fg $bg
client.urgent $secondary $secondary $fg $secondary

# XWayland
{xwayland_flag}

# Input
input type:touchpad tap enable
input type:pointer accel_profile flat

# Autostart
exec swaybg -i /usr/share/hope/wallpapers/deep-space.png -m fill

"#,
        xwayland_flag = if config.xwayland { "xwayland enable" } else { "xwayland disable" }
    );

    let config_path = config_dir.join("config");
    std::fs::write(&config_path, sway_config)?;
    info!("Sway config written to {}", config_path.display());

    Ok(())
}

/// Check if a Wayland session is available
pub fn is_wayland_session() -> bool {
    std::env::var("WAYLAND_DISPLAY").is_ok()
}

/// Get current display server info
pub fn display_info() -> String {
    if let Ok(display) = std::env::var("WAYLAND_DISPLAY") {
        format!("Wayland display: {}", display)
    } else if let Ok(display) = std::env::var("DISPLAY") {
        format!("X11 display: {} (no Wayland)", display)
    } else {
        "No display server detected".to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn backend_parse() {
        let mut config = CompositorConfig {
            backend: "river".to_string(),
            ..Default::default()
        };
        // This will fail if river isn't installed, but tests the logic
        let _ = detect_backend(&config);

        config.backend = "sway".to_string();
        let _ = detect_backend(&config);
    }

    #[test]
    fn display_info_works() {
        let info = display_info();
        assert!(!info.is_empty());
    }
}
